name: VİTOS Otomatik Güncelleme

on:
  push:
    branches:
      - main  

jobs:
  otomatik-cekme:
    runs-on: self-hosted 
    
    steps:
      - name: Dizin Sahipliğini Güvenli Yap
        run: git config --global --add safe.directory F:/REPO_GitHub/Cagatay_22.02

      - name: Yeni Kodu Çek
        working-directory: F:\REPO_GitHub\Cagatay_22.02
        run: git pull origin main